# Generated by Django 5.1.4 on 2025-01-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_driver_remove_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, help_text='The tag of the vehicle', max_length=50, null=True),
        ),
    ]
