# Generated by Django 5.1.4 on 2025-01-28 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
        ('vehicles', '0003_vehicle_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_driver', to='employeers.employeer'),
        ),
    ]
