# Generated by Django 5.1.4 on 2025-01-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='drivers_license',
            field=models.CharField(blank=True, help_text='The driver license of the vehicle', max_length=50, null=True),
        ),
    ]
