# Generated by Django 5.1.4 on 2025-01-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehicle_vehicle_color_vehicle_vehicle_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_maker',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_model',
        ),
    ]
