# Generated by Django 5.1.4 on 2025-01-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companie_created_by_companie_updated_by_and_more'),
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='complete_address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='companie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('Brazil', 'Brazil'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Peru', 'Peru'), ('Paraguay', 'Paraguay'), ('Venezuela', 'Venezuela'), ('Other', 'Other')], default='USA', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer'),
        ),
    ]
