# Generated by Django 5.1.4 on 2025-01-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeer',
            name='companie',
        ),
        migrations.RemoveField(
            model_name='employeer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employeer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='employeer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employeer',
            name='updated_by',
        ),
    ]
