# Generated by Django 5.1.4 on 2025-01-25 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0004_alter_brand_options'),
        ('categories', '0002_alter_category_options'),
        ('companies', '0004_companie_created_by_companie_updated_by_and_more'),
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
        ('inflows', '0003_remove_inflow_product_remove_inflow_quantity_and_more'),
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('brand', models.ForeignKey(help_text='The brand of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='brand.brand')),
                ('category', models.ForeignKey(help_text='The category of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='categories.category')),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('inflow', models.ForeignKey(help_text='The inflow of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inflows.inflow')),
                ('inflow_items', models.ForeignKey(help_text='The inflow items of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inflows.inflowitems')),
                ('outflow', models.ForeignKey(help_text='The outflow of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='outflows.outflow')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'ordering': ['-created_at'],
            },
        ),
    ]
