# Generated by Django 5.1.4 on 2025-01-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
