# Generated by Django 5.1.4 on 2025-01-25 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_companie_created_by_companie_updated_by_and_more'),
        ('customers', '0008_rename_name_customer_first_name_customer_last_name'),
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
        ('product', '0001_initial'),
        ('warehouse', '0002_alter_warehouseproduct_current_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The quantity of the product that is being removed from the warehouse')),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('destiny', models.ForeignKey(blank=True, help_text='The customer of the outflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows_destiny', to='customers.customer')),
                ('origin', models.ForeignKey(blank=True, help_text='The warehouse of the outflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows_origin', to='warehouse.warehouse')),
                ('product', models.ForeignKey(blank=True, help_text='The product of the outflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows', to='product.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
