# Generated by Django 5.1.5 on 2025-02-15 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('customers', '0001_initial'),
        ('employeers', '0001_initial'),
        ('product', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the outflow', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if outflow was rejected', null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('destiny', models.ForeignKey(blank=True, help_text='The customer of the outflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows_destiny', to='customers.customer')),
                ('origin', models.ForeignKey(blank=True, help_text='The warehouse of the outflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outflows_origin', to='warehouse.warehouse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutflowItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The quantity of that will be transfered')),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('outflow', models.ForeignKey(help_text='id of the outflow the item is part of', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outflows.outflow')),
                ('product', models.ForeignKey(help_text='the products that are going out of the warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='outflow_items', to='product.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
