# Generated by Django 5.1.4 on 2025-01-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
        ('product', '0002_productsku'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutflowItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The quantity of that will be transfered')),
                ('outflow', models.ForeignKey(help_text='id of the outflow the item is part of', on_delete=django.db.models.deletion.CASCADE, related_name='outflow_items', to='outflows.outflow')),
                ('product', models.ForeignKey(help_text='the products that are going out of the warehouse', on_delete=django.db.models.deletion.CASCADE, related_name='outflow_items', to='product.product')),
            ],
        ),
    ]
