# Generated by Django 5.1.4 on 2025-01-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0003_outflowitems_companie_outflowitems_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outflow',
            name='product',
        ),
        migrations.RemoveField(
            model_name='outflow',
            name='quantity',
        ),
    ]
