# Generated by Django 5.1.4 on 2025-01-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0004_remove_outflow_product_remove_outflow_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflowitems',
            name='outflow',
            field=models.ForeignKey(help_text='id of the outflow the item is part of', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outflows.outflow'),
        ),
    ]
