# Generated by Django 5.1.4 on 2025-02-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0005_alter_outflowitems_outflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='outflow',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if outflow was rejected', null=True),
        ),
        migrations.AddField(
            model_name='outflow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the outflow', max_length=20),
        ),
    ]
