# Generated by Django 4.2.9 on 2025-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Owner', 'Owner'), ('Admin', 'System Administrator'), ('Manager', 'Manager'), ('HR', 'Human Resources'), ('Accountant', 'Accountant'), ('Employee', 'Employee'), ('Installer', 'Installer'), ('Installer_Helper', 'Installer Helper'), ('Stock_Controller', 'Stock Controller'), ('Stocker', 'Stocker'), ('Salesman', 'Salesman'), ('Driver', 'Driver'), ('Delivery_Helper', 'Delivery Helper')], help_text='Department of the user in the company', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Owner', 'Owner'), ('Admin', 'System Administrator'), ('Manager', 'Manager'), ('HR', 'Human Resources'), ('Accountant', 'Accountant'), ('Employee', 'Employee'), ('Installer', 'Installer'), ('Installer_Helper', 'Installer Helper'), ('Stock_Controller', 'Stock Controller'), ('Stocker', 'Stocker'), ('Salesman', 'Salesman'), ('Driver', 'Driver'), ('Delivery_Helper', 'Delivery Helper')], help_text='Current position of the user', max_length=100),
        ),
    ]
