# Generated by Django 4.2.9 on 2025-02-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_department_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('Executive_Board', 'Executive Board'), ('Finance_Treasury', 'Finance and Treasury'), ('Accounting_Tax', 'Accounting and Tax'), ('HR_Development', 'HR and Development'), ('IT_Innovation', 'IT and Innovation'), ('Legal_Compliance', 'Legal and Compliance'), ('Sales_Marketing', 'Sales and Marketing'), ('Customer_Success', 'Customer Success'), ('Estimating_Proposals', 'Estimating and Proposals'), ('Project_Management', 'Project Management'), ('Installation_Services', 'Installation Services'), ('Technical_Support', 'Technical Support'), ('Quality_Control', 'Quality Control'), ('Warehouse_Operations', 'Warehouse Operations'), ('Inventory_Management', 'Inventory Management'), ('Logistics_Distribution', 'Logistics and Distribution'), ('Procurement_Supply', 'Procurement and Supply'), ('Health_Safety', 'Health and Safety'), ('Facilities_Maintenance', 'Facilities and Maintenance'), ('Training_Development', 'Training and Development')], help_text='Department of the user in the company', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('General_Manager', 'General Manager'), ('Financial_Analyst', 'Financial Analyst'), ('HR_Specialist', 'HR Specialist'), ('IT_Specialist', 'IT Specialist'), ('Administrative_Assistant', 'Administrative Assistant'), ('Sales_Manager', 'Sales Manager'), ('Sales_Consultant', 'Sales Consultant'), ('Project_Estimator', 'Project Estimator'), ('Operations_Manager', 'Operations Manager'), ('Project_Manager', 'Project Manager'), ('Site_Supervisor', 'Site Supervisor'), ('Master_Installer', 'Master Installer'), ('Senior_Installer', 'Senior Installer'), ('Junior_Installer', 'Junior Installer'), ('Installer_Assistant', 'Installer Assistant'), ('Warehouse_Manager', 'Warehouse Manager'), ('Inventory_Controller', 'Inventory Controller'), ('Logistics_Coordinator', 'Logistics Coordinator'), ('Delivery_Driver', 'Delivery Driver'), ('Warehouse_Assistant', 'Warehouse Assistant'), ('Quality_Inspector', 'Quality Inspector'), ('Safety_Coordinator', 'Safety Coordinator')], help_text='Current position of the user', max_length=100),
        ),
    ]
