# Generated by Django 4.2.9 on 2025-02-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_own_profile', 'Can view own profile only'), ('change_own_profile', 'Can edit own profile only')], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
