# Generated by Django 5.1.4 on 2025-01-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
