# Generated by Django 5.1.4 on 2025-01-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferitems',
            name='transfer',
            field=models.ForeignKey(blank=True, help_text='id of the transfer the item is part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='transfer.transfer'),
        ),
    ]
