# Generated by Django 5.1.4 on 2025-01-15 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Companie', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='companie',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companie',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companie',
            name='country',
            field=models.CharField(blank=True, default='USA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='companie',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companie',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companie',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companie',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='companie',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companie',
            name='type',
            field=models.CharField(blank=True, choices=[('headquarters', 'Headquarters'), ('subsidiary', 'Subsidiary')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PickUpCompanieAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_address', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_up_companie_address_companie', to='companies.companie')),
            ],
            options={
                'verbose_name': 'Pick Up Companie Address',
                'verbose_name_plural': 'Pick Up Companie Addresses',
                'ordering': ['-created_at'],
            },
        ),
    ]
