# Generated by Django 5.1.4 on 2025-01-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_hr_daily_salary_hr_hourly_salary_hr_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='daily_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='hourly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
