# Generated by Django 5.1.4 on 2025-01-17 08:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
        ('hr', '0003_alter_hr_daily_salary_alter_hr_hourly_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='daily_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Daily salary amount if paid by day', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='employeer',
            field=models.ForeignKey(blank=True, help_text='Employee associated with this HR record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_employeer', to='employeers.employeer'),
        ),
        migrations.AlterField(
            model_name='hr',
            name='hourly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Hourly salary amount if paid by hour', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the HR record', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hr',
            name='made_by',
            field=models.ForeignKey(blank=True, help_text='User who created/modified this HR record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_made_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hr',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Monthly salary amount if paid by month', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='payd_by_day',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if employee is paid on a daily basis', null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='payd_by_hour',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if employee is paid on an hourly basis', null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='payd_by_month',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if employee is paid on a monthly basis', null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', null=True),
        ),
    ]
