# Generated by Django 5.1.4 on 2025-01-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_hr_created_at_alter_hr_daily_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='current_period_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount to be paid for the current period', max_digits=10),
        ),
        migrations.AddField(
            model_name='hr',
            name='days_worked',
            field=models.PositiveIntegerField(default=0, help_text='Number of days worked in the current payment period'),
        ),
        migrations.AddField(
            model_name='hr',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Number of hours worked in the current payment period', max_digits=10),
        ),
        migrations.AddField(
            model_name='hr',
            name='last_day_registered',
            field=models.DateField(blank=True, help_text='Last day registered as worked', null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='last_hours_registered',
            field=models.DateTimeField(blank=True, help_text='Last time hours were registered', null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='last_payment_date',
            field=models.DateField(blank=True, help_text='Date of the last payment made', null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='payment_day',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], help_text='Day of the month when payment is due', null=True),
        ),
    ]
