# Generated by Django 5.1.4 on 2025-01-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_hr_current_period_amount_hr_days_worked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date worked')),
                ('hr', models.ForeignKey(help_text='HR record this worked day belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='worked_days', to='hr.hr')),
            ],
            options={
                'verbose_name': 'Worked Day',
                'verbose_name_plural': 'Worked Days',
                'ordering': ['-date'],
                'unique_together': {('hr', 'date')},
            },
        ),
    ]
