# Generated by Django 5.1.4 on 2025-01-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_workedday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='payment_day',
        ),
        migrations.AddField(
            model_name='hr',
            name='payment_business_day',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Business Day'), (2, '2nd Business Day'), (3, '3rd Business Day'), (4, '4th Business Day'), (5, '5th Business Day')], default=2, help_text='Which business day the payment should be made'),
        ),
        migrations.AddField(
            model_name='hr',
            name='payment_interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='monthly', help_text='Interval between payments (daily, weekly, biweekly, monthly)', max_length=10),
        ),
    ]
