# Generated by Django 5.1.4 on 2025-01-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_hr_payment_day_hr_payment_business_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='days_worked',
            field=models.PositiveIntegerField(default=0, help_text='Number of days worked since last payment'),
        ),
    ]
