# Generated by Django 5.1.4 on 2025-01-17 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_hr_days_worked'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date worked')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Hours worked on this day', max_digits=10)),
                ('hr', models.ForeignKey(help_text='HR record this worked hour belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='worked_hours', to='hr.hr')),
            ],
            options={
                'verbose_name': 'Worked Hour',
                'verbose_name_plural': 'Worked Hours',
                'ordering': ['-date'],
                'unique_together': {('hr', 'date')},
            },
        ),
    ]
