# Generated by Django 5.1.4 on 2025-01-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_workhour'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhour',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of the worked hour', null=True),
        ),
        migrations.AddField(
            model_name='workhour',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time of the worked hour', null=True),
        ),
    ]
