# Generated by Django 5.1.4 on 2025-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_alter_workhour_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours worked on this day', max_digits=10, null=True),
        ),
    ]
