# Generated by Django 5.1.4 on 2025-01-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_alter_workhour_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Date of the next payment due', null=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='payment_interval',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', help_text='Interval between payments (daily, weekly, biweekly, monthly)', max_length=10),
        ),
    ]
