# Generated by Django 5.1.4 on 2025-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_hr_next_payment_date_alter_hr_payment_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid to the employee', max_digits=10),
        ),
    ]
