# Generated by Django 5.1.4 on 2025-01-22 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_pickupcompanieaddress_created_at_and_more'),
        ('hr', '0015_paymenthistory_workhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='companie',
            field=models.ForeignKey(blank=True, help_text='Company associated with this HR record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_companie', to='companies.companie'),
        ),
    ]
