# Generated by Django 5.1.4 on 2025-01-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_hr_companie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='payment_interval',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly')], default='weekly', help_text='Interval between payments (daily, weekly, biweekly, monthly)', max_length=10),
        ),
    ]
