# Generated by Django 5.1.5 on 2025-02-15 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('employeers', '0001_initial'),
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the inflow', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if inflow was rejected', null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('destiny', models.ForeignKey(blank=True, help_text='The warehouse of the inflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflows_destiny', to='warehouse.warehouse')),
                ('origin', models.ForeignKey(blank=True, help_text='The supplier of the inflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflows_origin', to='supplier.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Inflow',
                'verbose_name_plural': 'Inflows',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_inflow', 'Can approve inflow'), ('can_reject_inflow', 'Can reject inflow'), ('can_generate_inflow_reports', 'Can generate inflow reports')],
            },
        ),
        migrations.CreateModel(
            name='InflowItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The quantity of this product coming in')),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('inflow', models.ForeignKey(help_text='id of the inflow the item is part of', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inflows.inflow')),
                ('product', models.ForeignKey(help_text='The products that are coming into stock', on_delete=django.db.models.deletion.CASCADE, related_name='inflow_items', to='product.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Inflow Item',
                'verbose_name_plural': 'Inflow Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
