# Generated by Django 5.1.4 on 2025-01-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
        ('product', '0001_initial'),
        ('supplier', '0004_alter_supplier_name_alter_supplier_tax_number'),
        ('warehouse', '0002_alter_warehouseproduct_current_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inflow', 'verbose_name_plural': 'Inflows'},
        ),
        migrations.AddField(
            model_name='inflow',
            name='destiny',
            field=models.ForeignKey(blank=True, help_text='The warehouse of the inflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflows_destiny', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='inflow',
            name='origin',
            field=models.ForeignKey(blank=True, help_text='The supplier of the inflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflows_origin', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='inflow',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product of the inflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inflows', to='product.product'),
        ),
        migrations.AddField(
            model_name='inflow',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='The quantity of the product that is being received'),
        ),
    ]
