# Generated by Django 5.1.4 on 2025-01-25 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companie_created_by_companie_updated_by_and_more'),
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
        ('inflows', '0002_alter_inflow_options_inflow_destiny_inflow_origin_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflow',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inflow',
            name='quantity',
        ),
        migrations.CreateModel(
            name='InflowItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The quantity of this product coming in')),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('inflow', models.ForeignKey(help_text='id of the inflow the item is part of', on_delete=django.db.models.deletion.CASCADE, related_name='inflow_items', to='inflows.inflow')),
                ('product', models.ForeignKey(help_text='The products that are coming into stock', on_delete=django.db.models.deletion.CASCADE, related_name='inflow_items', to='product.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Inflow Item',
                'verbose_name_plural': 'Inflow Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
