# Generated by Django 5.1.4 on 2025-01-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0003_remove_inflow_product_remove_inflow_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflowitems',
            name='inflow',
            field=models.ForeignKey(help_text='id of the inflow the item is part of', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inflows.inflow'),
        ),
    ]
