# Generated by Django 5.1.4 on 2025-02-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0005_inflow_rejection_reason_inflow_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_inflow', 'Can view inflow'), ('can_manage_inflow', 'Can manage inflow'), ('can_approve_inflow', 'Can approve inflow'), ('can_reject_inflow', 'Can reject inflow'), ('can_generate_inflow_reports', 'Can generate inflow reports')], 'verbose_name': 'Inflow', 'verbose_name_plural': 'Inflows'},
        ),
    ]
