# Generated by Django 5.1.4 on 2025-01-28 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_companie_created_by_companie_updated_by_and_more'),
        ('customers', '0010_customerbillingaddress_companie_and_more'),
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
        ('product', '0002_productsku'),
        ('vehicles', '0010_vehicle_vehicle_color_vehicle_vehicle_maker_and_more'),
        ('warehouse', '0003_alter_warehouseproduct_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.CharField(blank=True, help_text='The number of the delivery', max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], help_text='The status of the delivery', max_length=100, null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('destiny', models.ForeignKey(blank=True, help_text='The customer of the delivery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_destiny', to='customers.customer')),
                ('origin', models.ForeignKey(blank=True, help_text='The warehouse of the delivery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_origin', to='warehouse.warehouse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
                ('vehicle', models.ForeignKey(blank=True, help_text='The vehicle of the delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_vehicle', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('basement', models.PositiveIntegerField(default=0)),
                ('first_floor', models.PositiveIntegerField(default=0)),
                ('second_floor', models.PositiveIntegerField(default=0)),
                ('third_floor', models.PositiveIntegerField(default=0)),
                ('fourth_floor', models.PositiveIntegerField(default=0)),
                ('attic', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Delivery Item',
                'verbose_name_plural': 'Delivery Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
