# Generated by Django 5.1.4 on 2025-01-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitems',
            name='fifth_floor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
