# Generated by Django 4.2.9 on 2025-02-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, help_text='Actual delivery time of the delivery', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, help_text='Actual start time of the delivery', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, help_text='Estimated delivery time of the delivery', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_start_time',
            field=models.DateTimeField(blank=True, help_text='Estimated start time of the delivery', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_tracking_enabled',
            field=models.BooleanField(default=True, help_text='If real-time tracking is enabled for this delivery'),
        ),
    ]
