# Generated by Django 5.1.4 on 2025-01-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_deliveryitems_fifth_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryitems',
            name='fifth_floor',
        ),
    ]
