# Generated by Django 5.1.4 on 2025-01-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_remove_deliveryitems_fifth_floor'),
        ('vehicles', '0010_vehicle_vehicle_color_vehicle_vehicle_maker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='The vehicle of the delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_driver', to='vehicles.vehicle'),
        ),
    ]
