# Generated by Django 4.2.9 on 2025-02-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='store_number',
            field=models.CharField(blank=True, help_text='The store number of the supplier', max_length=50, null=True),
        ),
    ]
