# Generated by Django 5.1.4 on 2025-01-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, help_text='The tax number of the supplier', max_length=50, null=True),
        ),
    ]
