# Generated by Django 5.1.4 on 2025-02-10 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_pickupcompanieaddress_companie'),
        ('employeers', '0009_alter_employeer_hire_date'),
        ('product', '0004_product_price'),
        ('supplier', '0004_alter_supplier_name_alter_supplier_tax_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Current price per unit', max_digits=10)),
                ('last_purchase_date', models.DateField(auto_now=True, help_text='Date of last purchase')),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current price')),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('product', models.ForeignKey(help_text='The product', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='product.product')),
                ('supplier', models.ForeignKey(help_text='The supplier', on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='supplier.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Supplier Product Price',
                'verbose_name_plural': 'Supplier Product Prices',
                'ordering': ['-created_at'],
                'unique_together': {('supplier', 'product', 'is_current')},
            },
        ),
    ]
