# Generated by Django 5.1.4 on 2025-02-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_pickupcompanieaddress_companie'),
        ('employeers', '0009_alter_employeer_hire_date'),
        ('product', '0004_product_price'),
        ('supplier', '0005_supplierproductprice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierproductprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='supplierproductprice',
            name='is_current',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this is the current price'),
        ),
        migrations.AddIndex(
            model_name='supplierproductprice',
            index=models.Index(fields=['supplier', 'product', 'is_current'], name='supplier_su_supplie_77fb08_idx'),
        ),
    ]
