# Generated by Django 5.1.4 on 2025-01-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_alter_brand_created_at_alter_brand_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-created_at'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
