# Generated by Django 5.1.4 on 2025-01-25 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_companie_created_by_companie_updated_by_and_more'),
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
        ('product', '0002_productsku'),
        ('warehouse', '0002_alter_warehouseproduct_current_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('destiny', models.ForeignKey(blank=True, help_text='The warehouse of the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_destiny', to='warehouse.warehouse')),
                ('origin', models.ForeignKey(blank=True, help_text='The warehouse of the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_origin', to='warehouse.warehouse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The quantity of that will be transfered')),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('product', models.ForeignKey(help_text='the products that are coming into stock', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='product.product')),
                ('transfer', models.ForeignKey(blank=True, help_text='id of the transfer the item is part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_items', to='transfer.transfer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Transfer Item',
                'verbose_name_plural': 'Transfer Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
