# Generated by Django 5.1.4 on 2025-02-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_transferitems_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if transfer was rejected', null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the transfer', max_length=20),
        ),
    ]
