# Generated by Django 5.1.4 on 2025-02-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productsku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.PositiveIntegerField(default=0, help_text='The maximum quantity of the product that should be in stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0, help_text='The minimum quantity of the product that should be in stock'),
        ),
    ]
