# Generated by Django 5.1.4 on 2025-02-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0006_alter_inflow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_inflow', 'Can approve inflow'), ('can_reject_inflow', 'Can reject inflow'), ('can_generate_inflow_reports', 'Can generate inflow reports')], 'verbose_name': 'Inflow', 'verbose_name_plural': 'Inflows'},
        ),
    ]
