# Generated by Django 4.2.9 on 2025-02-25 15:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('companies', '0003_alter_companie_type'),
        ('employeers', '0003_alter_employeer_user'),
        ('deliveries', '0002_delivery_actual_delivery_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocationUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='GPS coordinates (longitude, latitude)', srid=4326)),
                ('accuracy', models.FloatField(blank=True, help_text='Accuracy of the location in meters', null=True)),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Heading in degrees (0-360)', null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('delivery', models.ForeignKey(help_text='The delivery associated with this location update', on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='deliveries.delivery')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
                ('vehicle', models.ForeignKey(help_text='The vehicle that sent this location update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_updates', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Location Update',
                'verbose_name_plural': 'Location Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('failed', 'Failed')], help_text='The new status of the delivery', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the status change', null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('delivery', models.ForeignKey(help_text='The delivery associated with this status update', on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='deliveries.delivery')),
                ('location_update', models.ForeignKey(blank=True, help_text='The location update associated with this status change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to='tracking.deliverylocationupdate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Status Update',
                'verbose_name_plural': 'Status Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('estimated_distance', models.FloatField(blank=True, help_text='Estimated distance in km', null=True)),
                ('estimated_duration', models.DurationField(blank=True, help_text='Estimated duration of the trip', null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, help_text='Estimated arrival time', null=True)),
                ('route_geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, help_text='Route geometry as LineString', null=True, srid=4326)),
                ('route_data', models.JSONField(blank=True, help_text='Additional route data in JSON format', null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('delivery', models.OneToOneField(help_text='The delivery associated with this route', on_delete=django.db.models.deletion.CASCADE, related_name='route', to='deliveries.delivery')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Delivery Route',
                'verbose_name_plural': 'Delivery Routes',
                'ordering': ['-created_at'],
            },
        ),
    ]
