# Generated by Django 5.1.4 on 2025-02-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_price'),
        ('warehouse', '0004_alter_warehouse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseproduct',
            options={'ordering': ['warehouse', 'product'], 'verbose_name': 'Warehouse Product', 'verbose_name_plural': 'Warehouse Products'},
        ),
        migrations.AlterUniqueTogether(
            name='warehouseproduct',
            unique_together={('warehouse', 'product')},
        ),
    ]
