# Generated by Django 5.1.4 on 2025-01-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='current_quantity',
            field=models.BigIntegerField(blank=True, default=0, help_text='The current quantity of this product in the warehouse', null=True),
        ),
    ]
