# Generated by Django 5.1.4 on 2025-01-28 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_warehouseproduct_current_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.warehouse'),
        ),
    ]
