# Generated by Django 5.1.4 on 2025-01-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the vehicle', max_length=50, null=True),
        ),
    ]
