# Generated by Django 5.1.4 on 2025-01-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(blank=True, choices=[('Truck', 'Truck'), ('Van', 'Van'), ('Car', 'Car'), ('SUV', 'SUV'), ('Pickup', 'Pickup')], help_text='The type of the delivery vehicle', max_length=50, null=True),
        ),
    ]
