# Generated by Django 5.1.4 on 2025-01-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_drivers_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_maker',
            field=models.CharField(blank=True, choices=[('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Dodge', 'Dodge'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Jeep', 'Jeep'), ('Mitsubishi', 'Mitsubishi'), ('Kia', 'Kia'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Lexus', 'Lexus'), ('Infiniti', 'Infiniti'), ('Subaru', 'Subaru'), ('GMC', 'GMC'), ('Mazda', 'Mazda'), ('Pontiac', 'Pontiac'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Saturn', 'Saturn'), ('GMC', 'GMC'), ('Chrysler', 'Chrysler'), ('Porsche', 'Porsche'), ('Jeep', 'Jeep'), ('Maserati', 'Maserati'), ('Lotus', 'Lotus'), ('Suzuki', 'Suzuki'), ('Scion', 'Scion'), ('Hummer', 'Hummer'), ('Saturn', 'Saturn'), ('GMC', 'GMC'), ('Chrysler', 'Chrysler'), ('Porsche', 'Porsche'), ('Jeep', 'Jeep'), ('Maserati', 'Maserati'), ('Lotus', 'Lotus'), ('Suzuki', 'Suzuki'), ('Scion', 'Scion'), ('Hummer', 'Hummer')], help_text='The maker of the vehicle', max_length=50, null=True),
        ),
    ]
