# Generated by Django 5.1.4 on 2025-01-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_vehicle_is_active_vehicle_vehicle_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Other', 'Other')], help_text='The color of the vehicle', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='The model of the vehicle', max_length=50, null=True),
        ),
    ]
