# Generated by Django 5.1.4 on 2025-01-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_remove_vehicle_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Other', 'Other')], help_text='The color of the vehicle', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_maker',
            field=models.CharField(blank=True, choices=[('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Dodge', 'Dodge'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Jeep', 'Jeep'), ('Mitsubishi', 'Mitsubishi'), ('Kia', 'Kia'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Lexus', 'Lexus'), ('Infiniti', 'Infiniti'), ('Subaru', 'Subaru'), ('GMC', 'GMC'), ('Mazda', 'Mazda'), ('Pontiac', 'Pontiac'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Saturn', 'Saturn'), ('GMC', 'GMC'), ('Chrysler', 'Chrysler'), ('Porsche', 'Porsche'), ('Jeep', 'Jeep'), ('Maserati', 'Maserati'), ('Lotus', 'Lotus'), ('Suzuki', 'Suzuki'), ('Scion', 'Scion'), ('Hummer', 'Hummer'), ('Saturn', 'Saturn'), ('GMC', 'GMC'), ('Chrysler', 'Chrysler'), ('Porsche', 'Porsche'), ('Jeep', 'Jeep'), ('Maserati', 'Maserati'), ('Lotus', 'Lotus'), ('Suzuki', 'Suzuki'), ('Scion', 'Scion'), ('Hummer', 'Hummer')], help_text='The maker of the vehicle', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='The model of the vehicle', max_length=50, null=True),
        ),
    ]
