# Generated by Django 5.1.4 on 2025-01-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_vehicle_color_vehicle_vehicle_maker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemilagehistory',
            name='milage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The milage of the vehicle', max_digits=10, null=True),
        ),
    ]
