# Generated by Django 5.2 on 2025-04-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerleads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerleads',
            options={'ordering': ['-created_at', 'status'], 'verbose_name': 'Customer Lead', 'verbose_name_plural': 'Customer Leads'},
        ),
        migrations.AlterField(
            model_name='customerleads',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerleads',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerleads',
            name='hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerleads',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerleads',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerleads',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerleads',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerleads',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerleads',
            name='reviews',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerleads',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
