# Generated by Django 5.1.4 on 2025-01-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerprojectaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprojectaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
