# Generated by Django 5.1.4 on 2025-01-30 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendanceregister'),
        ('employeers', '0007_remove_employeer_is_active_employeer_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystracking',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_employeer', to='employeers.employeer'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_employeer', to='employeers.employeer'),
        ),
    ]
