# Generated by Django 5.1.4 on 2025-01-31 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_daystracking_register_timetracking_register'),
        ('employeers', '0007_remove_employeer_is_active_employeer_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='days_worked',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='hours_worked',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daystracking',
            name='clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daystracking',
            name='employee',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_employeer', to='employeers.employeer'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='employee',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_employeer', to='employeers.employeer'),
        ),
    ]
