# Generated by Django 5.1.4 on 2025-01-31 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_payroll_hours_worked'),
        ('employeers', '0007_remove_employeer_is_active_employeer_hire_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceregister',
            options={'ordering': ['-created_at'], 'verbose_name': 'Attendance Register', 'verbose_name_plural': 'Attendance Registers'},
        ),
        migrations.AlterModelOptions(
            name='daystracking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Days Tracking', 'verbose_name_plural': 'Days Trackings'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payroll', 'verbose_name_plural': 'Payrolls'},
        ),
        migrations.AlterModelOptions(
            name='payrollhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payroll History', 'verbose_name_plural': 'Payroll Histories'},
        ),
        migrations.AlterModelOptions(
            name='timetracking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Time Tracking', 'verbose_name_plural': 'Time Trackings'},
        ),
        migrations.AddField(
            model_name='payroll',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_payroll', to='attendance.attendanceregister'),
        ),
        migrations.AddField(
            model_name='payrollhistory',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_payroll_history', to='attendance.attendanceregister'),
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_employeer', to='employeers.employeer'),
        ),
        migrations.AlterField(
            model_name='daystracking',
            name='employee',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days_tracking_employeer', to='employeers.employeer'),
        ),
        migrations.AlterField(
            model_name='daystracking',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days_tracking', to='attendance.attendanceregister'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_payroll_employeer', to='employeers.employeer'),
        ),
        migrations.AlterField(
            model_name='payrollhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_payroll_history_employeer', to='employeers.employeer'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='employee',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_time_tracking_employeer', to='employeers.employeer'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_time_tracking', to='attendance.attendanceregister'),
        ),
    ]
