# Generated by Django 5.1.5 on 2025-02-15 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('companies', '0001_initial'),
        ('employeers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregister',
            name='companie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie'),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_employeer', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='attendanceregister',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='daystracking',
            name='companie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie'),
        ),
        migrations.AddField(
            model_name='daystracking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='daystracking',
            name='employee',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days_tracking_employeer', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='daystracking',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days_tracking', to='attendance.attendanceregister'),
        ),
        migrations.AddField(
            model_name='daystracking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='companie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_payroll_employeer', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_payroll', to='attendance.attendanceregister'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='payrollhistory',
            name='companie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie'),
        ),
        migrations.AddField(
            model_name='payrollhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='payrollhistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_payroll_history_employeer', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='payrollhistory',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_history', to='attendance.payroll'),
        ),
        migrations.AddField(
            model_name='payrollhistory',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_payroll_history', to='attendance.attendanceregister'),
        ),
        migrations.AddField(
            model_name='payrollhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='companie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='employee',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_time_tracking_employeer', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_time_tracking', to='attendance.attendanceregister'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer'),
        ),
    ]
