# Generated by Django 5.1.4 on 2025-01-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_daystracking_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daystracking',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_tracking', to='attendance.attendanceregister'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_tracking', to='attendance.attendanceregister'),
        ),
    ]
