# Generated by Django 5.1.4 on 2025-01-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_payroll_days_worked_payroll_hours_worked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystracking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
