# Generated by Django 5.1.4 on 2025-01-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_daystracking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
