# Generated by Django 5.1.4 on 2025-01-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
        ('inventory', '0001_initial'),
        ('outflows', '0002_outflowitems'),
        ('product', '0002_productsku'),
        ('transfer', '0001_initial'),
        ('warehouse', '0002_alter_warehouseproduct_current_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='outflow_items',
            field=models.ForeignKey(help_text='The outflow items of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='outflows.outflowitems'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(help_text='The product of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='product.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_sku',
            field=models.ForeignKey(help_text='The product sku of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='product.productsku'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='transfer',
            field=models.ForeignKey(help_text='The transfer of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='transfer.transfer'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='transfer_items',
            field=models.ForeignKey(help_text='The transfer items of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='transfer.transferitems'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(help_text='The warehouse of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse_product',
            field=models.ForeignKey(help_text='The warehouse product of the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='warehouse.warehouseproduct'),
        ),
    ]
