# Generated by Django 4.2.9 on 2025-03-24 09:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_companie_type'),
        ('vehicle', '0002_remove_vehiclemaintenancerecord_companie_and_more'),
        ('customers', '0002_alter_customerbillingaddress_customer_and_more'),
        ('employeers', '0003_alter_employeer_user'),
        ('load_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pickup_in_progress', 'Pickup In Progress'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('failed', 'Failed')], default='pending', help_text='The status of the delivery', max_length=35)),
                ('current_location', models.JSONField(blank=True, help_text='Latitude/Longitude', null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('customer', models.ForeignKey(help_text='The customer that the delivery is for', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='customers.customer')),
                ('driver', models.ForeignKey(help_text='The driver that the delivery is for', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='employeers.employeer')),
                ('load', models.ManyToManyField(help_text='The load that the delivery is for', related_name='delivery', to='load_order.loadorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
                ('vehicle', models.ForeignKey(help_text='The vehicle that the delivery is for', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pickup_in_progress', 'Pickup In Progress'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('failed', 'Failed')], max_length=35)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='checkpoints/')),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='delivery.delivery')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Delivery Checkpoint',
                'verbose_name_plural': 'Delivery Checkpoints',
                'ordering': ['-created_at'],
            },
        ),
    ]
