# Generated by Django 5.1.4 on 2025-01-14 15:14

import django.contrib.auth.models
import django.contrib.auth.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(blank=True, choices=[('CEO', 'CEO'), ('Owner', 'Owner'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('HR', 'HR'), ('Accountant', 'Accountant'), ('Employee', 'Employee'), ('Stock_Controller', 'Stock Controller'), ('Stocker', 'Stocker'), ('Salesman', 'Salesman'), ('Driver', 'Driver'), ('Deliveryman', 'Deliveryman'), ('Customer', 'Customer'), ('Supplier', 'Supplier')], default='Employee', max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='normaluser_set', related_query_name='normaluser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='normaluser_set', related_query_name='normaluser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['is_active'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
