# Generated by Django 5.1.4 on 2025-01-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_normaluser_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaluser',
            options={'ordering': ['-is_active']},
        ),
    ]
