# Generated by Django 4.2.9 on 2025-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('CEO', 'Company CEO'), ('Owner', 'Company Owner'), ('Admin', 'System Administrator'), ('Manager', 'Manager'), ('HR', 'Human Resources'), ('Accountant', 'Accountant'), ('Employee', 'Employee'), ('Installer', 'Installer'), ('Installer_Helper', 'Installer Helper'), ('Stock_Controller', 'Stock Controller'), ('Stocker', 'Stocker'), ('Salesman', 'Sales man'), ('Driver', 'Driver'), ('Delivery_Helper', 'Delivery Helper'), ('Customer', 'Customer'), ('Supplier', 'Supplier')], max_length=100, null=True),
        ),
    ]
