# Generated by Django 5.1.4 on 2025-01-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_normaluser_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normaluser',
            old_name='type',
            new_name='user_type',
        ),
    ]
