# Generated by Django 4.2.9 on 2025-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('CEO', 'Company CEO'), ('Owner', 'Company Owner'), ('Admin', 'System Administrator'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Installer', 'Installer'), ('Stocker', 'Stocker'), ('Salesman', 'Sales man'), ('Driver', 'Driver'), ('Customer', 'Customer'), ('Supplier', 'Supplier')], max_length=100, null=True),
        ),
    ]
