# Generated by Django 4.2.9 on 2025-03-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemaintenancerecord',
            name='companie',
        ),
        migrations.RemoveField(
            model_name='vehiclemaintenancerecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehiclemaintenancerecord',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='vehiclemaintenancerecord',
            name='vehicle',
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['plate_number'], 'permissions': [('assign_driver', 'Can assign drivers to vehicles'), ('update_status', 'Can update vehicle status')], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity_volume',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity_weight',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_level',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_expiry',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='next_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='odometer',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='registration_expiry',
        ),
        migrations.DeleteModel(
            name='VehicleFuelRecord',
        ),
        migrations.DeleteModel(
            name='VehicleMaintenanceRecord',
        ),
    ]
