# Generated by Django 5.2 on 2025-08-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_remove_vehiclemaintenancerecord_companie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='maker',
            field=models.CharField(choices=[('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('Dodge', 'Dodge'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Nissan', 'Nissan'), ('Jeep', 'Jeep'), ('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Lexus', 'Lexus'), ('Subaru', 'Subaru'), ('GMC', 'GMC'), ('Mazda', 'Mazda'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chrysler', 'Chrysler'), ('Porsche', 'Porsche'), ('Mitsubishi', 'Mitsubishi'), ('Kia', 'Kia')], help_text='Manufacturer of the vehicle', max_length=50),
        ),
    ]
