# Generated by Django 5.1.4 on 2025-01-28 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_companie_created_by_companie_updated_by_and_more'),
        ('customers', '0008_rename_name_customer_first_name_customer_last_name'),
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
        ('warehouse', '0003_alter_warehouseproduct_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.CharField(blank=True, help_text='The number of the delivery', max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], help_text='The status of the delivery', max_length=100, null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('delivery_address', models.ForeignKey(blank=True, help_text='The delivery address of the delivery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_delivery_address', to='customers.customerprojectaddress')),
                ('destiny', models.ForeignKey(blank=True, help_text='The customer of the delivery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_destiny', to='customers.customer')),
                ('origin', models.ForeignKey(blank=True, help_text='The warehouse of the delivery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_origin', to='warehouse.warehouse')),
                ('pick_up_address', models.ForeignKey(blank=True, help_text='The pick up address of the delivery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_pick_up_address', to='companies.pickupcompanieaddress')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
