# Generated by Django 5.1.5 on 2025-02-15 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employeers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companie',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companie_created_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='companie',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companie_updated_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='pickupcompanieaddress',
            name='companie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companie_pick_up_address', to='companies.companie'),
        ),
    ]
