# Generated by Django 5.1.4 on 2025-01-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_companie_options_companie_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupcompanieaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickupcompanieaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
