# Generated by Django 4.2.9 on 2025-02-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companie',
            name='type',
            field=models.CharField(blank=True, choices=[('Headquarters', 'Headquarters'), ('Subsidiary', 'Subsidiary')], default='Headquarters', max_length=50, null=True),
        ),
    ]
