# Generated by Django 5.2 on 2025-08-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companie',
            name='country',
            field=models.CharField(blank=True, choices=[('USA', 'USA'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('Brazil', 'Brazil'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Peru', 'Peru'), ('Paraguay', 'Paraguay'), ('Other', 'Other')], default='USA', max_length=100, null=True),
        ),
    ]
