# Generated by Django 5.1.4 on 2025-01-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_pickupcompanieaddress_created_at_and_more'),
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='companie',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companie_created_by', to='employeers.employeer'),
        ),
        migrations.AddField(
            model_name='companie',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companie_updated_by', to='employeers.employeer'),
        ),
        migrations.AlterField(
            model_name='companie',
            name='country',
            field=models.CharField(blank=True, choices=[('USA', 'USA'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('Brazil', 'Brazil'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Peru', 'Peru'), ('Paraguay', 'Paraguay'), ('Venezuela', 'Venezuela'), ('Other', 'Other')], default='USA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companie',
            name='type',
            field=models.CharField(blank=True, choices=[('Headquarters', 'Headquarters'), ('Subsidiary', 'Subsidiary')], max_length=50, null=True),
        ),
    ]
