# Generated by Django 5.1.4 on 2025-02-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companie_created_by_companie_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupcompanieaddress',
            name='companie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companie_pick_up_address', to='companies.companie'),
        ),
    ]
