# Generated by Django 5.1.4 on 2025-01-23 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_state'),
        ('employeers', '0002_alter_employeer_options_employeer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='another_billing_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='another_shipping_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, choices=[('USA', 'USA'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('Brazil', 'Brazil'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Peru', 'Peru'), ('Paraguay', 'Paraguay'), ('Venezuela', 'Venezuela'), ('Other', 'Other')], default='USA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprojectaddress',
            name='country',
            field=models.CharField(blank=True, choices=[('USA', 'USA'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('Brazil', 'Brazil'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Peru', 'Peru'), ('Paraguay', 'Paraguay'), ('Venezuela', 'Venezuela'), ('Other', 'Other')], default='USA', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CustomerBillingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=155, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, choices=[('USA', 'USA'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('Brazil', 'Brazil'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Peru', 'Peru'), ('Paraguay', 'Paraguay'), ('Venezuela', 'Venezuela'), ('Other', 'Other')], default='USA', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_billing_address_created_by', to='employeers.employeer')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_billing_address_customer', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_billing_address_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Customer Billing Address',
                'verbose_name_plural': 'Customer Billing Addresses',
                'ordering': ['-created_at'],
            },
        ),
    ]
