# Generated by Django 5.1.4 on 2025-02-03 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customerbillingaddress_companie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbillingaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_billing_address', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='customerprojectaddress',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_project_address', to='customers.customer'),
        ),
    ]
