# Generated by Django 4.2.9 on 2025-02-24 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeers', '0003_alter_employeer_user'),
        ('companies', '0003_alter_companie_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('origin', models.CharField(blank=True, help_text='Origin of the movement', max_length=50, null=True)),
                ('destination', models.CharField(blank=True, help_text='Destination of the movement', max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Exit', 'Exit'), ('Transfer', 'Transfer')], help_text='Type of movement (Entry, Exit, Transfer)', max_length=20, null=True)),
                ('data', models.JSONField(blank=True, help_text='Data of the movement', null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], help_text='Current status of the movement', max_length=20, null=True)),
                ('total_items', models.PositiveIntegerField(blank=True, default=0, help_text='Total number of items in this movement', null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total value of items in this movement', max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date when the movement occurred', null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['type'], name='movements_m_type_6a0cec_idx'), models.Index(fields=['status'], name='movements_m_status_9c3411_idx'), models.Index(fields=['date'], name='movements_m_date_bbd847_idx'), models.Index(fields=['data'], name='movements_m_data_f0e988_idx')],
            },
        ),
    ]
