# Generated by Django 4.2.9 on 2025-03-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movement',
        ),
    ]
