# Generated by Django 5.1.4 on 2025-02-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['purchase_order', 'created_at'], 'verbose_name': 'Purchase Order Item', 'verbose_name_plural': 'Purchase Order Items'},
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery',
            field=models.DateField(blank=True, help_text='Expected delivery date', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(auto_now_add=True, help_text='Date when the order was placed', null=True),
        ),
        migrations.DeleteModel(
            name='SupplierProductPrice',
        ),
    ]
