# Generated by Django 5.1.4 on 2025-02-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_alter_purchaseorderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total value of the purchase order', max_digits=10),
        ),
    ]
