# Generated by Django 5.1.5 on 2025-02-15 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('categories', '0001_initial'),
        ('companies', '0001_initial'),
        ('employeers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='The description of the product', null=True)),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The total quantity of the product')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Current price of the product', max_digits=10)),
                ('min_quantity', models.PositiveIntegerField(default=0, help_text='The minimum quantity of the product that should be in stock')),
                ('max_quantity', models.PositiveIntegerField(default=0, help_text='The maximum quantity of the product that should be in stock')),
                ('brand', models.ForeignKey(blank=True, help_text='The brand of the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='brand.brand')),
                ('category', models.ForeignKey(blank=True, help_text='The category of the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category')),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('sku', models.CharField(blank=True, help_text='The sku of the product', max_length=100, null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('product', models.ForeignKey(help_text='The product of the sku', on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='product.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Product Sku',
                'verbose_name_plural': 'Product Skus',
                'ordering': ['-created_at'],
            },
        ),
    ]
