# Generated by Django 4.2.9 on 2025-02-17 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companie_type'),
        ('supplier', '0002_supplier_store_number'),
        ('employeers', '0001_initial'),
        ('product', '0002_productsupplierid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInStoreID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('in_store_id', models.CharField(blank=True, help_text='The id of the product in the supplier store', max_length=100, null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(help_text='The suppliers of the product', related_name='products', to='supplier.supplier'),
        ),
        migrations.DeleteModel(
            name='ProductSupplierID',
        ),
        migrations.AddField(
            model_name='productinstoreid',
            name='product',
            field=models.ForeignKey(help_text='The product of the sku', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ids', to='product.product'),
        ),
        migrations.AddField(
            model_name='productinstoreid',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer'),
        ),
    ]
