# Generated by Django 4.2.9 on 2025-02-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_store_number'),
        ('product', '0003_productinstoreid_product_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='The suppliers of the product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='supplier.supplier'),
        ),
    ]
