# Generated by Django 4.2.9 on 2025-02-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_supplier_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinstoreid',
            name='product',
            field=models.ForeignKey(help_text='The product of the sku', on_delete=django.db.models.deletion.CASCADE, related_name='store_ids', to='product.product'),
        ),
    ]
