# Generated by Django 5.1.5 on 2025-02-15 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('customers', '0001_initial'),
        ('employeers', '0001_initial'),
        ('product', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_number', models.CharField(blank=True, help_text='The order number of the load order', max_length=100, null=True)),
                ('load_date', models.DateField(blank=True, help_text='The date of the load order', null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('customer', models.ForeignKey(blank=True, help_text='The customer that the load order is going to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('load_to', models.ForeignKey(blank=True, help_text='The vehicle that the load order is going to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Load Order',
                'verbose_name_plural': 'Load Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='The quantity of the product that the item is', max_digits=10)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('load_order', models.ForeignKey(help_text='The load order that the item is part of', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='load_order.loadorder')),
                ('product', models.ForeignKey(blank=True, help_text='The product that the item is', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_order_product', to='product.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Load Order Item',
                'verbose_name_plural': 'Load Order Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
