# Generated by Django 5.1.4 on 2025-01-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadorder',
            name='load_date',
            field=models.DateField(blank=True, help_text='The date of the load order', null=True),
        ),
    ]
