# Generated by Django 4.2.9 on 2025-02-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employeer',
            name='date_of_birth',
        ),
    ]
