# Generated by Django 5.1.4 on 2025-01-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeer',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employeer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
