# Generated by Django 4.2.9 on 2025-02-21 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employeers', '0002_remove_employeer_age_remove_employeer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeer', to=settings.AUTH_USER_MODEL),
        ),
    ]
