# Generated by Django 5.1.4 on 2025-01-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0003_remove_employeer_companie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employeer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employeer',
            name='zip_code',
        ),
    ]
