# Generated by Django 5.2 on 2025-08-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0003_alter_employeer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeer',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada'), ('Mexico', 'Mexico'), ('Brazil', 'Brazil'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Ecuador', 'Ecuador'), ('Peru', 'Peru'), ('Paraguay', 'Paraguay'), ('Other', 'Other')], default='USA', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeer',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Hour', 'By Hour')], max_length=50, null=True),
        ),
    ]
