# Generated by Django 5.1.4 on 2025-01-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0005_employeer_address_employeer_city_employeer_companie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeer',
            options={'ordering': ['name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RenameField(
            model_name='employeer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='employeer',
            name='last_name',
        ),
    ]
