# Generated by Django 5.1.4 on 2025-01-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0006_alter_employeer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='employeer',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeer',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Hour', 'By Hour'), ('Day', 'By Day')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeer',
            name='payroll_schedule',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeer',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
