# Generated by Django 5.1.4 on 2025-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0007_remove_employeer_is_active_employeer_hire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeer',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
