# Generated by Django 5.1.4 on 2025-02-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeers', '0008_employeer_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeer',
            name='hire_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
