# Generated by Django 5.1.5 on 2025-02-15 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('employeers', '0001_initial'),
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_number', models.CharField(blank=True, help_text='The order number of the purchase order', max_length=100, null=True)),
                ('order_date', models.DateField(auto_now_add=True, help_text='Date when the order was placed', null=True)),
                ('expected_delivery', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', help_text='Current status of the purchase order', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the order, including reason for rejection', null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total value of the purchase order', max_digits=10)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('supplier', models.ForeignKey(help_text='Supplier providing the products', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='supplier.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_order', 'Can approve order'), ('can_reject_order', 'Can reject order'), ('can_cancel_order', 'Can cancel order'), ('can_add_item', 'Can add item'), ('can_update_item', 'Can update item'), ('can_remove_item', 'Can remove item')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Agreed price per unit', max_digits=10)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('product', models.ForeignKey(help_text='The product being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='product.product')),
                ('purchase_order', models.ForeignKey(help_text='The related purchase order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_order.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'ordering': ['purchase_order', 'created_at'],
            },
        ),
    ]
