# Generated by Django 5.1.4 on 2025-02-10 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_alter_pickupcompanieaddress_companie'),
        ('employeers', '0009_alter_employeer_hire_date'),
        ('product', '0004_product_price'),
        ('supplier', '0004_alter_supplier_name_alter_supplier_tax_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order_date', models.DateField(help_text='Date when the order was placed')),
                ('expected_delivery', models.DateField(help_text='Expected delivery date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', help_text='Current status of the purchase order', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the order', null=True)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('supplier', models.ForeignKey(help_text='Supplier providing the products', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='supplier.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Agreed price per unit', max_digits=10)),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('product', models.ForeignKey(help_text='The product being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='product.product')),
                ('purchase_order', models.ForeignKey(help_text='The related purchase order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_order.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Current price per unit', max_digits=10)),
                ('last_purchase_date', models.DateField(auto_now=True, help_text='Date of last purchase')),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current price')),
                ('companie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_companie', to='companies.companie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to='employeers.employeer')),
                ('product', models.ForeignKey(help_text='The product', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='product.product')),
                ('supplier', models.ForeignKey(help_text='The supplier', on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='supplier.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to='employeers.employeer')),
            ],
            options={
                'verbose_name': 'Supplier Product Price',
                'verbose_name_plural': 'Supplier Product Prices',
                'ordering': ['-created_at'],
                'unique_together': {('supplier', 'product', 'is_current')},
            },
        ),
    ]
