# Generated by Django 5.1.4 on 2025-02-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_purchaseorder_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(blank=True, help_text='The order number of the purchase order', max_length=100, null=True),
        ),
    ]
