# Generated by Django 5.1.5 on 2025-02-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_purchaseorder_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_order', 'Can approve order'), ('can_reject_order', 'Can reject order'), ('can_cancel_order', 'Can cancel order'), ('can_add_item', 'Can add item'), ('can_update_item', 'Can update item'), ('can_remove_item', 'Can remove item')], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
    ]
