# Generated by Django 5.1.5 on 2025-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_purchaseorder_approved_at_purchaseorder_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rejection_reason',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the order, including reason for rejection', null=True),
        ),
    ]
