name: Django ERP CI/CD

on:
  push:
    branches: [ "main", "Dev" ]
  pull_request:
    branches: [ "main", "Dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: erp_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r BackEnd/requirements.txt
        pip install flake8 black isort coverage
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Check code formatting with Black
      run: |
        black --check .
    
    - name: Check imports with isort
      run: |
        isort --check-only --profile black .
    
    - name: Run Migrations
      run: |
        python manage.py migrate
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/erp_test
    
    - name: Run Base Tests
      run: |
        python manage.py test core accounts companies --keepdb
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/erp_test
    
    - name: Run Inventory Module Tests
      run: |
        python manage.py test inventory --keepdb
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/erp_test
    
    - name: Run HR Module Tests
      run: |
        python manage.py test employeers attendance --keepdb
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/erp_test
    
    - name: Run Logistics Module Tests
      run: |
        python manage.py test logistics customers suppliers vehicle --keepdb
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/erp_test
    
    - name: Run Coverage Report
      run: |
        coverage run --source='.' manage.py test
        coverage report
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/erp_test
